language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "13.12.0"
deploy:
  provider: script
  script: gatsby build && gh-pages -d public -b master
  skip_cleanup: true
  on:
    branch: master
